# This is required for the autoconfiguration to kick in, should be overwritten in application-secret.yml
spring:
  main:
    banner-mode: off
  mail:
    host: example.com
logging:
  level:
    root: INFO

internal:
  default-subject: "Secret santa!"
  default-from: "SecretSanta <me@example.com>"
  default-email: me@example.com
  participant-file-location: "classpath:participants/participants.json"
  text-template: "Hi {who}! You're a secret santa for {giftFor} this year!"
  do-send: false
  use-test-email: false
  max-shuffles: 100000
